# Generated by Django 2.1.5 on 2019-02-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20190223_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placemap',
            name='places',
            field=models.ManyToManyField(blank=True, to='places.Place'),
        ),
    ]
