# Generated by Django 2.1.5 on 2019-02-26 14:52

from django.db import migrations, models

from django.utils.text import slugify


def set_user_slugs(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    for user in CustomUser.objects.all():
        slug = orig = slugify(user.name)
        counter = 1
        while CustomUser.objects.filter(slug=slug).exists():
            slug = '{}-{}'.format(orig, counter)
            counter += 1
        user.slug = slug
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='placeholder', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(max_length=70, null=True, unique=True),
        ),
        migrations.RunPython(set_user_slugs),
    ]
